### ISSUE TITLE
Package.json call to babel breaks more complex setups

### ISSUE THREAD

**Issue by qacwnfq** [TestArmada/testarmada-logger#1]
```   "build": "./node_modules/.bin/babel src --out-dir lib --source-maps", ```

This line breaks more complex setups with maven and the maven-frontend-plugin. The plugin calls npm and npm then can't find babel. It seems the relative paths don't work out correctly anymore.

In my example this breaks the installation of dpro@1.2.0.

See
```
[INFO] > testarmada-logger@1.0.0 postinstall /home/fjadebeck/repos/store-demo/integration-tests/src/test/frontends/shop/node_modules/dpro/node_modules/testarmada-logger
[INFO] > npm run build
[INFO] 
[INFO] 
[INFO] > testarmada-logger@1.0.0 build /home/fjadebeck/repos/demo/integration-tests/src/node_modules/dpro/node_modules/testarmada-logger
[INFO] > babel src --out-dir lib --source-maps
[INFO] 
[ERROR] sh: 1: babel: not found
[ERROR] 
[ERROR] npm ERR! Linux 4.9.0-0.bpo.2-amd64
```

I'm not sure if npm natively support expanding some variable into the correct absolute path or if a script is necessary.

**Comment by archlichking** [comment]
@qacwnfq what's your node and npm version in the build system? `babel` is supposed to be installed with https://github.com/TestArmada/logger/blob/master/package.json#L30

**Comment by qacwnfq** [comment]
I was using node v4.4.4 and npm 2.15.1 but now that I upgraded to node v6.9.4 and npm 3.10.10 everything works well!
